import React,{useState} from 'react';import{createRoot}from'react-dom/client';
import Sidebar from './src/components/dashboard/Sidebar';import ThemeToggle from './src/components/ThemeToggle';import {useWorkspaceTheme}from'./src/hooks/useWorkspaceTheme';import{supabase}from'./src/services/supabaseClient';
import './src/index.css';import './src/workspace.css';import './src/theme.css';
import Dashboard from './src/pages/Dashboard';
import Usuarios from './src/pages/Usuarios';
import AnalizarComentario from './src/pages/AnalizarComentario';
import PalabrasFrecuentes from './src/pages/PalabrasFrecuentes';
import Clientes from './src/pages/Clientes';
import Comentarios from './src/pages/Comentarios';
import Solicitudes from './src/pages/Solicitudes';
import TiemposAtencion from './src/pages/TiemposAtencion';
import Categorias from './src/pages/Categorias';
import Clasificacion from './src/pages/Clasificacion';
import Estadisticas from './src/pages/Estadisticas';
import Interpolacion from './src/pages/Interpolacion';
import Optimizacion from './src/pages/Optimizacion';
import Reportes from './src/pages/Reportes';
import Auditoria from './src/pages/Auditoria';
const users=[{id:1,nombre:'Ana García',email:'ana@example.test',rol:'Administrador',activo:true},{id:2,nombre:'Carlos López',email:'carlos@example.test',rol:'Analista',activo:true}];
const comments=[{id:1,contenido:'El servicio fue excelente y rápido',canal:'Web',estado:'Pendiente'},{id:2,contenido:'Tengo problemas con mi equipo',canal:'Web',estado:'Pendiente'},{id:3,contenido:'Necesito un asesor técnico',canal:'Correo',estado:'Pendiente'}];
supabase.auth.getUser=async()=>({data:{user:{id:'preview',email:'ana@example.test',user_metadata:{}}},error:null});
supabase.from=(table)=>{const data=table==='usuarios'?users:table==='comentarios'?comments:table==='clientes'?[{id:1,nombre:'Cliente de ejemplo',email:'cliente@example.test',telefono:'000000000',empresa:'Empresa de ejemplo'}]:[];const result={data,error:null};let proxy;proxy=new Proxy({}, {get:(_,key)=>key==='then'?Promise.resolve(result).then.bind(Promise.resolve(result)):key==='maybeSingle'?async()=>({data:users[0],error:null}):['insert','update','delete'].includes(key)?()=>{throw Error('Writes disabled in visual preview')}:()=>proxy});return proxy;};
supabase.channel=()=>{const c={on:()=>c,subscribe:()=>c};return c};supabase.removeChannel=async()=>{};
const components={'Dashboard':Dashboard,'Usuarios':Usuarios,'Analizar comentario':AnalizarComentario,'Palabras frecuentes':PalabrasFrecuentes,'Clientes':Clientes,'Comentarios':Comentarios,'Solicitudes':Solicitudes,'Tiempos de atención':TiemposAtencion,'Categorías NLP':Categorias,'Categorías Sistema':Categorias,'Clasificación':Clasificacion,'Estadísticas':Estadisticas,'Interpolación':Interpolacion,'Optimización':Optimizacion,'Reportes':Reportes,'Auditoria':Auditoria};
function Preview(){const[page,setPage]=useState('Dashboard');const[collapsed,setCollapsed]=useState(false);const[open,setOpen]=useState(false);const{theme,toggleTheme}=useWorkspaceTheme();const Page=components[page]||Dashboard;return <div className={'app '+(collapsed?'sidebar-collapsed':'')} data-theme={theme}><Sidebar activePage={page} setActivePage={setPage} collapsed={collapsed} onToggle={()=>setCollapsed(!collapsed)} isOpen={open} setIsOpen={setOpen}/><div className="content"><header className="workspace-topbar"><button className="icon-button mobile-menu-toggle" aria-label="Abrir menú" onClick={()=>setOpen(true)}>☰</button><span>Empresa Inteligente <span className="breadcrumb-divider">/</span><strong>{page}</strong></span><ThemeToggle theme={theme} onToggle={toggleTheme}/></header><Page/></div></div>};createRoot(document.getElementById('root')).render(<Preview/>);